services:
  sophia-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sophia-bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - TZ=America/Sao_Paulo
      - EVO_BASE_URL=http://evolution_api:8081  
      - EVO_API_TOKEN=${EVO_API_TOKEN}
      - EVO_INSTANCE_ID=${EVO_INSTANCE_ID}
      - EVO_INSTANCE_TOKEN=${EVO_INSTANCE_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - evolution-net  # Mesma rede utilizada pela Evolution API
    healthcheck:  
      test: ["CMD", "curl", "-f", "http://evolution_api:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  evolution-net:
    external: true